apiVersion: apps/v1
kind: Deployment
metadata:
  name: notjira-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notjira-front
  template:
    metadata:
      labels:
        app: notjira-front
    spec:
      containers:
      - name: notjira-front
        image: milosky/notjira-front:latest
        ports:
        - containerPort: 19006       
---
apiVersion: v1
kind: Service
metadata:
  name: notjira-front
spec:
  type: NodePort
  selector:
    app: notjira-front
  ports:
    - protocol: TCP
      port: 19006
      targetPort: 19006
